version: '3'

services:
  mailcatcher:
    container_name: ${APP_NAME}-mailcatcher
    image: schickling/mailcatcher
    ports:
      - ${MAILCATCHER_PORT}:1080

  test-postgres:
    container_name: ${APP_NAME}-postgres-test
    image: postgres:15-alpine
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
    ports:
      - ${TEST_POSTGRES_PORT}:5432
